import { Link } from "@/i18n/navigation";
import { notFound } from "next/navigation";
import { castVote } from "@/app/actions/votes";
import { ProductMark } from "@/components/product-mark";
import { ShareButton } from "@/components/share-button";
import { getMatch } from "@/lib/data";
import { createClient } from "@/lib/supabase/server";
import { roundLabel, votePercent } from "@/lib/utils";

export default async function MatchPage({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<{error?:string;voted?:string}> }) {
  const [{id},query] = await Promise.all([params,searchParams]);
  const match = await getMatch(id); if(!match) notFound();
  const supabase = await createClient();
  const { data: result } = await supabase.rpc("get_match_result", { target_match_id:id }).maybeSingle();
  const total = result ? Number(result.product_a_vote_count)+Number(result.product_b_vote_count):0;
  const closed = match.status === "completed" || match.status === "cancelled";
  return <div className="page-shell"><div style={{textAlign:"center",marginBottom:32}}><span className="eyebrow">{roundLabel(match.round_number)} · {match.status}</span><h1 style={{fontSize:"clamp(36px,5vw,62px)",margin:"10px 0"}}>Which would you rather try?</h1>{query.error&&<p className="form-message">{query.error}</p>}</div><div className="battle"><article className="battle-product"><ProductMark name={match.product_a.name} src={match.product_a.logo_url} size={74}/><span className="badge">{match.product_a.category}</span><h2>{match.product_a.name}</h2><strong>{match.product_a.tagline}</strong><p>{match.product_a.description}</p><Link target="_blank" className="button button-ghost" href={`/visit?product=${match.product_a.id}&match=${match.id}&url=${encodeURIComponent(match.product_a.url)}`}>Visit website ↗</Link></article><div className="battle-vs">VS</div><article className="battle-product"><ProductMark name={match.product_b.name} src={match.product_b.logo_url} size={74}/><span className="badge">{match.product_b.category}</span><h2>{match.product_b.name}</h2><strong>{match.product_b.tagline}</strong><p>{match.product_b.description}</p><Link target="_blank" className="button button-ghost" href={`/visit?product=${match.product_b.id}&match=${match.id}&url=${encodeURIComponent(match.product_b.url)}`}>Visit website ↗</Link></article></div>{result?<section className="panel" style={{marginTop:18}}><div className="result-bar"><i style={{width:`${votePercent(Number(result.product_a_vote_count),total)}%`}}/><i style={{width:`${votePercent(Number(result.product_b_vote_count),total)}%`}}/></div><div className="result-copy"><span>{votePercent(Number(result.product_a_vote_count),total)}% {match.product_a.name}</span><span>{match.product_b.name} {votePercent(Number(result.product_b_vote_count),total)}%</span></div><p className="muted" style={{textAlign:"center"}}>{total.toLocaleString()} votes · {closed?"Final result":"Voting in progress"}</p></section>:<div className="vote-row"><form action={castVote}><input type="hidden" name="matchId" value={match.id}/><input type="hidden" name="productId" value={match.product_a.id}/><button disabled={closed} className="button button-accent" style={{width:"100%"}}>Vote for {match.product_a.name}</button></form><span/><form action={castVote}><input type="hidden" name="matchId" value={match.id}/><input type="hidden" name="productId" value={match.product_b.id}/><button disabled={closed} className="button button-accent" style={{width:"100%"}}>Vote for {match.product_b.name}</button></form></div>}<p className="muted" style={{textAlign:"center",marginTop:18}}>Vote totals stay hidden until you vote or the match ends.</p><div style={{display:"flex",justifyContent:"center",marginTop:20}}><ShareButton matchId={match.id} productA={match.product_a.name} productB={match.product_b.name}/></div></div>;
}
