import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { updateProfile } from "@/app/actions/profile";
import { signOut } from "@/app/actions/auth";
import { AvatarUploader } from "@/components/avatar-uploader";
import { ProductMark } from "@/components/product-mark";
import { createClient } from "@/lib/supabase/server";

export default async function ProfileSettingsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/${locale}/login`);
  const { data: profile } = await supabase.from("profiles").select("*").eq("id", user.id).maybeSingle(); if (!profile) notFound();
  return <div className="page-shell"><div className="dashboard-grid"><aside className="side-nav"><Link href={`/${locale}/dashboard`}>My products</Link><Link href={`/${locale}/dashboard/profile`}>Profile</Link><Link href={`/${locale}/submit`}>Submit product</Link><Link href={`/${locale}/dashboard/account`}>Account</Link><form action={signOut}><button className="button button-ghost">Sign out</button></form></aside><section className="narrow"><span className="eyebrow">Profile</span><div className="section-head"><h1 style={{ fontSize: 58 }}>Your profile</h1><Link className="button button-ghost" href={`/${locale}/profile/${profile.username}`} target="_blank">Public preview ↗</Link></div><section className="panel" style={{ marginBottom: 22 }}><div className="profile-hero" style={{ marginBottom: 0 }}><ProductMark name={profile.display_name ?? profile.username} src={profile.avatar_url} size={72}/><div><strong>{profile.display_name ?? profile.username}</strong><br/><span className="muted">@{profile.username}</span><p className="muted" style={{ marginBottom: 0 }}>This is your signed-in preview.</p></div></div></section><form action={updateProfile} className="panel form"><input type="hidden" name="locale" value={locale}/><div className="form-row"><div className="field"><label>Display name</label><input name="displayName" defaultValue={profile.display_name ?? ""} required maxLength={80}/></div><div className="field"><label>Username</label><input name="username" defaultValue={profile.username} required minLength={3} maxLength={30}/></div></div><AvatarUploader currentUrl={profile.avatar_url}/><div className="field"><label>Bio</label><textarea name="bio" defaultValue={profile.bio ?? ""} maxLength={500}/></div><div className="field"><label>Website</label><input name="websiteUrl" type="url" defaultValue={profile.website_url ?? ""}/></div><div className="form-row"><div className="field"><label>X username</label><input name="xHandle" defaultValue={profile.x_handle ?? ""} maxLength={30}/></div><div className="field"><label>GitHub URL</label><input name="githubUrl" type="url" defaultValue={profile.github_url ?? ""}/></div></div><div className="field"><label>LinkedIn URL</label><input name="linkedinUrl" type="url" defaultValue={profile.linkedin_url ?? ""}/></div><button className="button button-accent">Save profile</button></form></section></div></div>;
}
