import { submitProduct } from "@/app/actions/products";
import { Dropdown } from "@/components/dropdown";

const categories = ["Developer Tools", "Productivity", "Design", "AI", "Marketing", "Finance", "Other"].map((value) => ({ value, label: value }));
const pricing = [["free", "Free"], ["freemium", "Freemium"], ["paid", "Paid"], ["contact", "Contact sales"]].map(([value, label]) => ({ value, label }));

export default function SubmitPage() {
  return <div className="page-shell narrow"><span className="eyebrow">For makers</span><h1>Enter your product</h1><p className="muted">Submit a product you own or operate. Every entry is reviewed before it joins an Arena.</p><form action={submitProduct} className="panel form" style={{ marginTop: 32 }} encType="multipart/form-data"><div className="form-row"><div className="field"><label>Product name *</label><input name="name" maxLength={80} required/></div><div className="field"><label>Website URL *</label><input name="url" type="url" placeholder="https://" required/></div></div><div className="field"><label>Tagline *</label><input name="tagline" maxLength={80} required/></div><div className="field"><label>Description *</label><textarea name="description" maxLength={2000} minLength={20} required/></div><div className="form-row"><div className="field"><label>Category *</label><Dropdown ariaLabel="Category" name="category" value="" options={categories} placeholder="Select" required/></div><div className="field"><label>Pricing</label><Dropdown ariaLabel="Pricing" name="pricingType" value="free" options={pricing}/></div></div><div className="form-row"><div className="field"><label>Logo *</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/></div><div className="field"><label>Primary screenshot *</label><input name="screenshot" type="file" accept="image/png,image/jpeg,image/webp" required/></div></div><button className="button button-accent">Submit for review</button></form></div>;
}
