import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createComment } from "@/app/actions/comments";
import { ProductMark } from "@/components/product-mark";
import { createClient } from "@/lib/supabase/server";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const db=await createClient();const {data}=await db.from("products").select("name,tagline").eq("slug",slug).maybeSingle();return {title:data?.name??"Product",description:data?.tagline};}

export default async function ProductPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{error?:string}>}){
  const [{slug},query]=await Promise.all([params,searchParams]); const supabase=await createClient();
  const {data:product}=await supabase.from("products").select("*, product_screenshots(*)").eq("slug",slug).maybeSingle(); if(!product)notFound();
  const [{data:comments},{data:stats}]=await Promise.all([supabase.from("product_comments").select("*,profile:profiles(display_name,username,avatar_url)").eq("product_id",product.id).is("deleted_at",null).order("created_at",{ascending:false}),supabase.rpc("get_product_stats",{target_product_id:product.id}).maybeSingle()]);
  return <div className="page-shell"><section className="profile-hero"><ProductMark name={product.name} src={product.logo_url} size={92}/><div><span className="eyebrow">{product.category}</span><h1 style={{fontSize:56,margin:"8px 0"}}>{product.name}</h1><p>{product.tagline}</p></div><Link href={`/visit?product=${product.id}&url=${encodeURIComponent(product.url)}`} target="_blank" className="button" style={{marginLeft:"auto"}}>Visit website ↗</Link></section><div className="grid" style={{gridTemplateColumns:"2fr 1fr"}}><section><div className="stack">{product.product_screenshots?.map((shot:{id:string;image_url:string})=><Image key={shot.id} src={shot.image_url} alt={`${product.name} screenshot`} width={900} height={560} style={{width:"100%",height:"auto",borderRadius:18,border:"1px solid var(--line)"}}/>)}</div><section className="panel" style={{marginTop:20}}><h2>About</h2><p style={{whiteSpace:"pre-wrap",lineHeight:1.7}}>{product.description}</p></section></section><aside className="panel"><h3>Performance</h3><div className="stack"><span><strong>{stats?.total_matches??0}</strong><br/><small className="muted">Matches</small></span><span><strong>{stats?.wins??0}</strong><br/><small className="muted">Wins</small></span><span><strong>{stats?.championships??0}</strong><br/><small className="muted">Championships</small></span></div></aside></div><section className="comments"><h2>Comments</h2>{query.error&&<p className="form-message">{query.error}</p>}<form action={createComment} className="form"><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="slug" value={slug}/><div className="field"><textarea name="body" placeholder="What do you think about this product?" required/></div><button className="button" style={{justifySelf:"start"}}>Post comment</button></form><div>{comments?.map(comment=><article className="comment" key={comment.id}><strong>{comment.profile?.display_name??comment.profile?.username??"Maker"}</strong><p>{comment.body}</p></article>)}</div></section></div>;
}
