create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text check (char_length(bio) <= 500),
  website_url text,
  x_handle text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id),
  name text not null check (char_length(name) between 2 and 80),
  slug text not null unique,
  url text not null,
  tagline text not null check (char_length(tagline) <= 80),
  description text not null check (char_length(description) <= 2000),
  logo_url text,
  category text not null,
  pricing_type text,
  x_url text,
  github_url text,
  demo_url text,
  maker_comment text,
  status text not null default 'draft' check (status in ('draft','submitted','under_review','approved','rejected','archived')),
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_screenshots (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0 check (sort_order between 0 and 4),
  created_at timestamptz not null default now(),
  unique(product_id, sort_order)
);

create table public.arenas (
  id uuid primary key default gen_random_uuid(),
  arena_number integer generated by default as identity unique,
  arena_size integer not null default 128 check (arena_size in (16,32,64,128)),
  status text not null default 'filling' check (status in ('filling','scheduled','active','completed','cancelled')),
  starts_at timestamptz,
  ends_at timestamptz,
  champion_product_id uuid references public.products(id),
  created_at timestamptz not null default now()
);

create table public.arena_entries (
  id uuid primary key default gen_random_uuid(),
  arena_id uuid references public.arenas(id) on delete cascade,
  product_id uuid not null references public.products(id),
  seed_number integer,
  status text not null default 'queued' check (status in ('queued','active','eliminated','champion','withdrawn')),
  eliminated_round integer,
  final_position integer,
  queued_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(arena_id, product_id)
);

create unique index one_open_entry_per_product on public.arena_entries(product_id)
where status in ('queued','active');

create table public.arena_queue (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null unique references public.products(id) on delete cascade,
  queued_at timestamptz not null default now()
);

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  arena_id uuid not null references public.arenas(id) on delete cascade,
  round_number integer not null check (round_number between 1 and 7),
  bracket_position integer not null,
  product_a_id uuid not null references public.products(id),
  product_b_id uuid not null references public.products(id),
  winner_product_id uuid references public.products(id),
  product_a_vote_count integer not null default 0,
  product_b_vote_count integer not null default 0,
  status text not null default 'scheduled' check (status in ('scheduled','active','overtime','completed','cancelled')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  overtime_ends_at timestamptz,
  tiebreak_type text check (tiebreak_type in ('votes','overtime','draw','walkover','manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(arena_id, round_number, bracket_position),
  check (product_a_id <> product_b_id)
);

create unique index one_active_match_per_product_a on public.matches(product_a_id) where status in ('scheduled','active','overtime');
create unique index one_active_match_per_product_b on public.matches(product_b_id) where status in ('scheduled','active','overtime');

create table public.votes (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.products(id),
  created_at timestamptz not null default now(),
  unique(match_id, user_id)
);

create table public.product_comments (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 2 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.outbound_clicks (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  match_id uuid references public.matches(id) on delete set null,
  user_id uuid references public.profiles(id) on delete set null,
  source text not null default 'product',
  created_at timestamptz not null default now()
);

create table public.access_grants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id text not null,
  gate_vote_count integer not null default 1,
  granted_at timestamptz not null default now(),
  expires_at timestamptz not null,
  unique(user_id, session_id)
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create table public.analytics_events (
  id bigint generated always as identity primary key,
  event_name text not null check (event_name in ('page_view','gate_impression','gate_vote','match_impression','vote','product_view','website_click','comment_create','product_submit','product_approved','match_share','arena_view')),
  user_id uuid references public.profiles(id) on delete set null,
  entity_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.app_settings(key,value) values
  ('arena_size','128'),('round_start_hour_utc','15'),('entry_required_votes','1');

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger products_touch before update on public.products for each row execute function public.touch_updated_at();
create trigger matches_touch before update on public.matches for each row execute function public.touch_updated_at();
create trigger comments_touch before update on public.product_comments for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles(id,username,display_name,avatar_url)
  values(new.id, 'maker-' || substr(new.id::text,1,8), coalesce(new.raw_user_meta_data->>'display_name',new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)), new.raw_user_meta_data->>'avatar_url');
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.queue_approved_product() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    insert into public.arena_queue(product_id) values(new.id) on conflict do nothing;
  end if;
  return new;
end $$;
create trigger products_queue_after_approval after update of status on public.products for each row execute function public.queue_approved_product();

create or replace function public.join_arena_queue(target_product_id uuid) returns void language plpgsql security definer set search_path = '' as $$
declare target public.products;
begin
  select * into target from public.products where id=target_product_id and owner_id=auth.uid();
  if target.id is null then raise exception 'Product not found or not owned by you'; end if;
  if target.status <> 'approved' then raise exception 'Product must be approved'; end if;
  if exists(select 1 from public.arena_entries where product_id=target_product_id and status in ('queued','active')) then raise exception 'Product is already in an Arena'; end if;
  if exists(select 1 from public.arena_entries where product_id=target_product_id and status='eliminated' and created_at > now()-interval '7 days') then raise exception 'This product is in its 7-day cooldown'; end if;
  insert into public.arena_queue(product_id) values(target_product_id) on conflict do nothing;
end $$;

create or replace function public.cast_vote(target_match_id uuid,target_product_id uuid) returns void language plpgsql security definer set search_path = '' as $$
declare current_match public.matches; owns_product boolean;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into current_match from public.matches where id=target_match_id for update;
  if current_match.id is null or current_match.status not in ('active','overtime') then raise exception 'Match is not active'; end if;
  if current_match.status='active' and now() >= current_match.ends_at then raise exception 'Voting has ended'; end if;
  if current_match.status='overtime' and now() >= current_match.overtime_ends_at then raise exception 'Overtime has ended'; end if;
  if target_product_id not in (current_match.product_a_id,current_match.product_b_id) then raise exception 'Invalid product'; end if;
  select exists(select 1 from public.products where owner_id=auth.uid() and id in (current_match.product_a_id,current_match.product_b_id)) into owns_product;
  if owns_product then raise exception 'Owners cannot vote in their own match'; end if;
  insert into public.votes(match_id,user_id,product_id) values(target_match_id,auth.uid(),target_product_id);
  update public.matches set
    product_a_vote_count=product_a_vote_count+(target_product_id=current_match.product_a_id)::integer,
    product_b_vote_count=product_b_vote_count+(target_product_id=current_match.product_b_id)::integer
  where id=target_match_id;
  insert into public.analytics_events(event_name,user_id,entity_id) values('vote',auth.uid(),target_match_id);
  if current_match.status='overtime' then
    update public.matches set status='completed',winner_product_id=target_product_id,tiebreak_type='overtime' where id=target_match_id;
  end if;
end $$;

create or replace function public.get_match_result(target_match_id uuid)
returns table(product_a_vote_count integer,product_b_vote_count integer) language plpgsql security definer set search_path = '' stable as $$
begin
  if not exists(select 1 from public.matches m where m.id=target_match_id and (m.status='completed' or exists(select 1 from public.votes v where v.match_id=m.id and v.user_id=auth.uid()))) then return; end if;
  return query select m.product_a_vote_count,m.product_b_vote_count from public.matches m where m.id=target_match_id;
end $$;

create or replace function public.get_product_stats(target_product_id uuid)
returns table(total_matches bigint,wins bigint,losses bigint,championships bigint,final_appearances bigint) language sql security definer set search_path = '' stable as $$
  select
    (select count(*) from public.matches m where target_product_id in(m.product_a_id,m.product_b_id)),
    (select count(*) from public.matches m where m.winner_product_id=target_product_id),
    (select count(*) from public.matches m where m.status='completed' and target_product_id in(m.product_a_id,m.product_b_id) and m.winner_product_id<>target_product_id),
    (select count(*) from public.arenas a where a.champion_product_id=target_product_id),
    (select count(*) from public.matches m join public.arenas a on a.id=m.arena_id where target_product_id in(m.product_a_id,m.product_b_id) and m.round_number=log(2,a.arena_size)::integer)
$$;

create or replace function public.create_arena_from_queue() returns uuid language plpgsql security definer set search_path = '' as $$
declare requested_size integer; new_arena uuid; start_time timestamptz; product_ids uuid[]; i integer; start_hour integer;
begin
  if not exists(select 1 from public.profiles where id=auth.uid() and role='admin') and auth.role()<>'service_role' then raise exception 'Admin required'; end if;
  select (value::text)::integer into requested_size from public.app_settings where key='arena_size';
  if (select count(*) from public.arena_queue) < requested_size then raise exception 'Not enough products in queue (% required)',requested_size; end if;
  select (value::text)::integer into start_hour from public.app_settings where key='round_start_hour_utc';
  start_time=date_trunc('day',now())+make_interval(hours=>start_hour);
  if start_time<=now() then start_time=start_time+interval '1 day'; end if;
  select array_agg(product_id order by gen_random_uuid()) into product_ids from (select product_id from public.arena_queue order by queued_at limit requested_size) q;
  insert into public.arenas(arena_size,status,starts_at,ends_at) values(requested_size,'scheduled',start_time,start_time+(log(2,requested_size)::integer)*interval '1 day') returning id into new_arena;
  for i in 1..requested_size loop
    insert into public.arena_entries(arena_id,product_id,seed_number,status) values(new_arena,product_ids[i],i,'active');
  end loop;
  for i in 1..(requested_size/2) loop
    insert into public.matches(arena_id,round_number,bracket_position,product_a_id,product_b_id,status,starts_at,ends_at)
    values(new_arena,1,i,product_ids[i*2-1],product_ids[i*2],case when start_time<=now() then 'active' else 'scheduled' end,start_time,start_time+interval '24 hours');
  end loop;
  delete from public.arena_queue where product_id=any(product_ids);
  return new_arena;
end $$;

create or replace function public.settle_due_matches() returns integer language plpgsql security definer set search_path = '' as $$
declare current_match public.matches; settled integer:=0; chosen uuid; max_round integer; next_position integer; pair_a uuid; pair_b uuid;
begin
  if auth.role()<>'service_role' and not exists(select 1 from public.profiles where id=auth.uid() and role='admin') then raise exception 'Server role required'; end if;
  update public.matches set status='active' where status='scheduled' and starts_at<=now();
  update public.arenas set status='active' where status='scheduled' and starts_at<=now();
  for current_match in select * from public.matches where (status='active' and ends_at<=now()) or (status='overtime' and overtime_ends_at<=now()) for update loop
    if current_match.product_a_vote_count=current_match.product_b_vote_count and current_match.status='active' then
      update public.matches set status='overtime',overtime_ends_at=now()+interval '30 minutes' where id=current_match.id;
      continue;
    end if;
    if current_match.product_a_vote_count>current_match.product_b_vote_count then chosen=current_match.product_a_id;
    elsif current_match.product_b_vote_count>current_match.product_a_vote_count then chosen=current_match.product_b_id;
    else chosen=case when random()<.5 then current_match.product_a_id else current_match.product_b_id end; end if;
    update public.matches set status='completed',winner_product_id=chosen,tiebreak_type=case when current_match.product_a_vote_count=current_match.product_b_vote_count then 'draw' else 'votes' end where id=current_match.id;
    update public.arena_entries set status='eliminated',eliminated_round=current_match.round_number where arena_id=current_match.arena_id and product_id in(current_match.product_a_id,current_match.product_b_id) and product_id<>chosen;
    settled=settled+1;
  end loop;
  for current_match in select distinct on(arena_id,round_number) * from public.matches where status='completed' order by arena_id,round_number desc loop
    if exists(select 1 from public.matches where arena_id=current_match.arena_id and round_number=current_match.round_number and status<>'completed') then continue; end if;
    select log(2,arena_size)::integer into max_round from public.arenas where id=current_match.arena_id;
    if current_match.round_number=max_round then
      select winner_product_id into chosen from public.matches where arena_id=current_match.arena_id and round_number=max_round;
      update public.arenas set status='completed',champion_product_id=chosen,ends_at=now() where id=current_match.arena_id and status<>'completed';
      update public.arena_entries set status='champion',final_position=1 where arena_id=current_match.arena_id and product_id=chosen;
    elsif not exists(select 1 from public.matches where arena_id=current_match.arena_id and round_number=current_match.round_number+1) then
      for next_position in 1..((select count(*) from public.matches where arena_id=current_match.arena_id and round_number=current_match.round_number)/2) loop
        select winner_product_id into pair_a from public.matches where arena_id=current_match.arena_id and round_number=current_match.round_number and bracket_position=next_position*2-1;
        select winner_product_id into pair_b from public.matches where arena_id=current_match.arena_id and round_number=current_match.round_number and bracket_position=next_position*2;
        insert into public.matches(arena_id,round_number,bracket_position,product_a_id,product_b_id,status,starts_at,ends_at) values(current_match.arena_id,current_match.round_number+1,next_position,pair_a,pair_b,'active',now(),now()+interval '24 hours');
      end loop;
    end if;
  end loop;
  return settled;
end $$;

create or replace view public.matches_public as select id,arena_id,round_number,bracket_position,product_a_id,product_b_id,winner_product_id,status,starts_at,ends_at,overtime_ends_at,tiebreak_type,created_at,updated_at from public.matches;
create or replace view public.product_rankings as
select p.id,p.name,p.slug,p.logo_url,
  (select count(*) from public.matches m where m.winner_product_id=p.id) wins,
  (select count(*) from public.arenas a where a.champion_product_id=p.id) championships,
  (select count(*) from public.matches m join public.arenas a on a.id=m.arena_id where p.id in(m.product_a_id,m.product_b_id) and m.round_number=log(2,a.arena_size)::integer) final_appearances,
  (select max(m.ends_at) from public.matches m where m.winner_product_id=p.id) latest_win
from public.products p where p.status='approved'
order by wins desc,championships desc,final_appearances desc,latest_win desc;

alter table public.profiles enable row level security;alter table public.products enable row level security;alter table public.product_screenshots enable row level security;
alter table public.arenas enable row level security;alter table public.arena_entries enable row level security;alter table public.arena_queue enable row level security;
alter table public.matches enable row level security;alter table public.votes enable row level security;alter table public.product_comments enable row level security;
alter table public.outbound_clicks enable row level security;alter table public.access_grants enable row level security;alter table public.audit_logs enable row level security;alter table public.analytics_events enable row level security;

create or replace function public.is_admin() returns boolean language sql security definer set search_path='' stable as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;

create policy "public profiles" on public.profiles for select using(true);create policy "own profile update" on public.profiles for update using(auth.uid()=id);
create policy "approved products public" on public.products for select using(status='approved' or owner_id=auth.uid() or public.is_admin());
create policy "users submit products" on public.products for insert to authenticated with check(owner_id=auth.uid());create policy "owners update products" on public.products for update to authenticated using(owner_id=auth.uid() and status<>'archived') with check(owner_id=auth.uid());
create policy "screenshots public" on public.product_screenshots for select using(exists(select 1 from public.products p where p.id=product_id and (p.status='approved' or p.owner_id=auth.uid())));create policy "owners add screenshots" on public.product_screenshots for insert to authenticated with check(exists(select 1 from public.products p where p.id=product_id and p.owner_id=auth.uid()));
create policy "arenas public" on public.arenas for select using(true);create policy "entries public" on public.arena_entries for select using(true);create policy "own queue visible" on public.arena_queue for select to authenticated using(public.is_admin() or exists(select 1 from public.products p where p.id=product_id and p.owner_id=auth.uid()));
create policy "matches public" on public.matches for select using(true);
create policy "comments public" on public.product_comments for select using(deleted_at is null);create policy "users comment" on public.product_comments for insert to authenticated with check(user_id=auth.uid());create policy "authors edit comments" on public.product_comments for update to authenticated using(user_id=auth.uid());
create policy "record clicks" on public.outbound_clicks for insert with check(user_id is null or user_id=auth.uid());create policy "own grants" on public.access_grants for select to authenticated using(user_id=auth.uid());create policy "create own grants" on public.access_grants for insert to authenticated with check(user_id=auth.uid());

grant select on public.matches_public,public.product_rankings to anon,authenticated;
revoke all on public.votes from anon,authenticated;grant execute on function public.cast_vote(uuid,uuid),public.get_match_result(uuid),public.get_product_stats(uuid),public.join_arena_queue(uuid) to authenticated;
grant execute on function public.get_match_result(uuid),public.get_product_stats(uuid) to anon;
revoke select on public.matches from anon,authenticated;
grant select(id,arena_id,round_number,bracket_position,product_a_id,product_b_id,winner_product_id,status,starts_at,ends_at,overtime_ends_at,tiebreak_type,created_at,updated_at) on public.matches to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-media','product-media',true,5242880,array['image/png','image/jpeg','image/webp']) on conflict do nothing;
create policy "product media public" on storage.objects for select using(bucket_id='product-media');
create policy "users upload product media" on storage.objects for insert to authenticated with check(bucket_id='product-media' and (storage.foldername(name))[1]=auth.uid()::text);

create index matches_status_ends_idx on public.matches(status,ends_at);create index arena_entries_product_idx on public.arena_entries(product_id,status);create index votes_match_idx on public.votes(match_id);create index products_status_created_idx on public.products(status,created_at);create index comments_product_created_idx on public.product_comments(product_id,created_at);
